require('core.config.lualine')
require('core.config.monokai')
require('core.config.tree')
require('core.config.telescope')
require('core.config.treesitter')
require('core.config.lsp')
require('core.config.completions')
require('core.config.presence')
